# Generated by Django 3.2.16 on 2023-02-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked_image',
            name='target',
            field=models.IntegerField(verbose_name='目标坐标'),
        ),
    ]
