# Generated by Django 3.2.16 on 2023-01-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
