# Generated by Django 3.2.16 on 2023-01-12 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0003_books_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid'),
        ),
    ]
