# Generated by Django 3.2.16 on 2023-01-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0005_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='checked_image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, verbose_name='图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='任务创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='任务更新时间')),
                ('result', models.IntegerField(default=0, verbose_name='检测结果')),
                ('category', models.SmallIntegerField(choices=[(0, '合格'), (1, '缺陷')], verbose_name='分类')),
                ('trust', models.FloatField(max_length=4, verbose_name='精度')),
                ('target', models.IntegerField(max_length=32, verbose_name='目标坐标')),
                ('image_result', models.CharField(max_length=255, verbose_name='检测后图片')),
            ],
        ),
        migrations.CreateModel(
            name='login_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('logout_time', models.DateTimeField(auto_now=True, verbose_name='退出时间')),
            ],
        ),
        migrations.CreateModel(
            name='task_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32, verbose_name='任务名称')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('complete_time', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
            ],
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.AddField(
            model_name='checked_image',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oAuth.task_info', verbose_name='任务'),
        ),
    ]
