# Generated by Django 3.2.16 on 2023-02-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0006_auto_20230128_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checked_image',
            name='task',
        ),
        migrations.DeleteModel(
            name='login_info',
        ),
        migrations.DeleteModel(
            name='checked_image',
        ),
        migrations.DeleteModel(
            name='task_info',
        ),
    ]
